### ISSUE TITLE
Incorrect assert

### ISSUE THREAD

**Issue by freak82** [arvidn/bdecode#1]
I think the assert 'TORRENT_ASSERT(header_size < 8);' in the bdecode_token constructor for string type is not correct.

When the string length is 7 digits it correctly passes the following check

// the bdecode_token only has 8 bits to keep the header size
// in. If it overflows, fail!
if (start - str_start - 2 > detail::bdecode_token::max_header)
    TORRENT_FAIL_BDECODE(bdecode_errors::limit_exceeded);

And then when the bdecode_token is constructed it asserts because the assert there doesn't take into accout the implied two characters - the first digit and the colon.

**Comment by arvidn** [comment]
nice catch! you don't happen to have a fuzzer for bencoding do you?

**Comment by arvidn** [comment]
fix is here: https://github.com/arvidn/libtorrent/pull/321

**Comment by arvidn** [comment]
I just realized this needs porting over to the stand-alone bdecode repo too
